import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Link from "next/link";
import { Code, Book, Music } from "lucide-react";
import { Badge } from "@/components/ui/badge";

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.className} antialiased min-h-screen bg-gradient-to-b from-gray-950 via-indigo-950 to-black text-white`}
            >
                <header className="bg-black/70 backdrop-blur-md py-4 px-6 flex justify-between items-center sticky top-0 z-10 border-b border-indigo-500/30">
                    <nav className="flex justify-between items-center w-full">
                        <Link href="/" className="flex items-center space-x-2">
                            <span className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 to-purple-600">
                                audio-visualizer.js
                            </span>
                            <Badge
                                variant="secondary"
                                className="bg-indigo-500/20 text-indigo-300 hover:bg-indigo-500/30"
                            >
                                v1.0.0
                            </Badge>
                        </Link>
                        <div className="flex space-x-6">
                            <Link
                                href="/docs"
                                className="text-indigo-300 hover:text-indigo-100 transition-colors flex items-center space-x-2"
                            >
                                <Book className="w-5 h-5" />
                                <span>Docs</span>
                            </Link>
                            <Link
                                href="/playground"
                                className="text-indigo-300 hover:text-indigo-100 transition-colors flex items-center space-x-2"
                            >
                                <Music className="w-5 h-5" />
                                <span>Playground</span>
                            </Link>
                            <a
                                href="https://github.com/your-repo"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-indigo-300 hover:text-indigo-100 transition-colors flex items-center space-x-2"
                            >
                                <Code className="w-5 h-5" />
                                <span>GitHub</span>
                            </a>
                        </div>
                    </nav>
                </header>
                {children}
                <footer className="bg-black/70 backdrop-blur-md py-8 border-t border-indigo-500/30">
                    <div className="container mx-auto px-6 text-center text-indigo-300">
                        <p>
                            © {new Date().getFullYear()} audio-visualizer.js.
                            All rights reserved.
                        </p>
                        <div className="mt-4 flex justify-center space-x-4">
                            <Link
                                href="/privacy"
                                className="text-sm hover:text-indigo-100 transition-colors"
                            >
                                Privacy Policy
                            </Link>
                            <Link
                                href="/terms"
                                className="text-sm hover:text-indigo-100 transition-colors"
                            >
                                Terms of Service
                            </Link>
                        </div>
                    </div>
                </footer>
            </body>
        </html>
    );
}
